#!/usr/bin/env bash

read -p "Enter the word: " word


query=$(curl -s "https://api.dictionaryapi.dev/api/v2/entries/en_US/$word")

[ -z "$query" ] && notify-send -h string:bgcolor:#bf616a -t 3000 "Invalid word." && exit 0

# Show only first 3 definitions
def=$(echo "$query" | jq -r '[.[].meanings[] | {pos: .partOfSpeech, def: .definitions[].definition}] | .[:10].[] | "\n\(.pos). \(.def)"')

# Show first definition for each part of speech (thanks @morgengabe1 on youtube)
# def=$(echo "$query" | jq -r '.[0].meanings[] | "\(.partOfSpeech): \(.definitions[0].definition)\n"')

# Show all definitions
# def=$(echo "$query" | jq -r '.[].meanings[] | "\n\(.partOfSpeech). \(.definitions[].definition)"')

# Regex + grep for just definition, if anyone prefers that to jq
# def=$(grep -Po '"definition":"\K(.*?)(?=")' <<< "$query")

bold=$(tput bold)
normal=$(tput sgr0)

echo "${bold}Definition of $word"
echo "${normal}$def"
echo

echo "Definition of $word" &>> list_of_looked_up_words
echo "$def" &>> list_of_looked_up_words
echo &>> list_of_looked_up_words
echo &>> list_of_looked_up_words
echo &>> list_of_looked_up_words

read var
        if [[ -n $var ]]
        then
                continue
        fi
done
